version: '3'

services:
  #############################################################################
  # Middlewares
  #############################################################################
  redis:
    image: redis:5.0.5-alpine3.9
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  #############################################################################
  # Databases
  #############################################################################
  transmart-database:
      image: postgres:11-alpine
      environment:
        POSTGRES_USER: biomart_user
        POSTGRES_PASSWORD: biomart_user
        POSTGRES_DB: transmart
      volumes:
        - transmart-db-data:/var/lib/postgresql/data

  gb-backend-database:
      image: postgres:11-alpine
      environment:
        POSTGRES_USER: gb
        POSTGRES_PASSWORD: gb
        POSTGRES_DB: gb_backend
      volumes:
        - db-data:/var/lib/postgresql/data

  #############################################################################
  # API Server for transmart
  #############################################################################
  transmart-api-server:
    image: thehyve/transmart-api-server:17.1-HYVE-5.9-RC3
    environment:
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}/auth
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      PGHOST: transmart-database
      PGPORT: 5432
      PGDATABASE: transmart
    depends_on:
      - transmart-database

  gb-backend:
    image: thehyve/glowing-bear-backend
    environment:
      TRANSMART_API_SERVER_URL: ${TRANSMART_API_SERVER_URL}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      DB_USER: gb
      DB_PASSWORD: gb
      DB_HOST: gb-backend-database
      DB_PORT: 5432
      DB_NAME: gb_backend
    depends_on:
      - gb-backend-database
      - transmart-api-server

  transmart-packer:
    image: thehyve/transmart-packer:0.1.3
    command: ['python', '-m', 'packer']
    depends_on:
      - redis
    environment:
      TRANSMART_URL: ${TRANSMART_API_SERVER_URL}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      CLIENT_ORIGIN_URL: '*'

  transmart-packer-worker:
    container_name: transmart-packer-worker
    image: thehyve/transmart-packer:0.1.3
    command:  ['celery', '-A', 'packer.tasks', 'worker', '-c', '4', '--loglevel', 'info']
    depends_on:
      - redis
    environment:
      TRANSMART_URL: ${TRANSMART_API_SERVER_URL}


  # # ----- glowing-bear -----
  # glowing-bear:
  #   image: thehyve/glowing-bear:1.3.8
  #   ports:
  #     - 80:80
  #   environment:
  #     TRANSMART_API_SERVER_URL: ${TRANSMART_API_SERVER_URL}
  #     TRANSMART_PACKER_URL: ${TRANSMART_PACKER_URL}
  #     GB_BACKEND_URL: ${GB_BACKEND_URL}
  #     KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
  #   # depends_on:
  #   #   - gb-backend
  #   #   - transmart-api-server
  #   #   - transmart-packer
  #   #optional volumes for ssl certificates, required if `NGINX_PORT=443 ssl`
  #   volumes:
  #     - ./nginx/server.crt:/etc/nginx/server.crt
  #     - ./nginx/server.key:/etc/nginx/server.key
  #     - ./nginx/ssl.conf:/etc/nginx/ssl.conf
  #   networks:
  #     - nginx-proxy-network




volumes:
  db-data:
  transmart-db-data:
  redis-data:
